name: Auto Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every day at midnight UTC (adjust for WAT if needed)
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest

    permissions:
    contents: write

      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "AVJoshua"
          git config user.email "akalihujoshua@gmail.com"

      - name: Update README with timestamp
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          echo "README updated on $(date)" >> README.md
          echo "Last updated: $DATE" >> README.md
          git add README.md
          git commit -m "Update README with timestamp: $DATE" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/AVJoshua/github-streak-automation.git HEAD:main
